package com.sanderxavalon.passwordvalidation.core.common.response;

public enum StatusEnum {
    SUCCESS(100,"SUCCESS"),
    FAIL(001,"FAIL"),
    PASSWORD_IS_NULL(20001,"PASSWORD IS NULL"),
    PASSWORD_IS_EMPTY(20002,"PASSWORD IS EMPTY"),
    PASSWORD_IS_LESS_THAN_MIN_REQUIRE(20003,"PASSWORD IS LESS THAN MIN REQUIRE"),
    PASSWORD_IS_MORE_THAN_MAX_REQUIRE(20004,"PASSWORD IS MORE THAN MAX REQUIRE"),
    PASSWORD_MUST_CONTAIN_ONE_LOWERCASE_LETTER(20005,"PASSWORD MUST CONTAIN ONE LOWERCASE LETTER"),
    PASSWORD_MUST_CONTAIN_ONE_NUMBER(20006,"PASSWORD MUST CONTAIN ONE NUMBER"),
    PASSWORD_MUST_NOT_CONTAIN_UPPERCASE_LETTER_OR_PUNCTUATION(20007,"PASSWORD MUST NOT CONTAIN UPPERCASE LETTER OR PUNCTUATION"),
    PASSWORD_MUST_NOT_CONTAIN_A_SEQUENCE_LETTER_FOLLOW_BY_ANY_SAME_SEQUENCE(20008,"PASSWORD MUST NOT CONTAIN A SEQUENCE LETTER FOLLOW BY ANY SAME SEQUENCE"),
    SYSTEM_NO_DEFAULT_VALUE_FOUND(90001, "SYSTEM NO DEFAULT VALUE FOUND"),
    ERROR(999,"ERROR");
    int status;
    String message;

    StatusEnum(int status, String message) {
        this.status = status;
        this.message = message;
    }

    public int getStatus() {
        return status;
    }

    public String getMessage() {
        return message;
    }
}
